import Head from "next/head";
import NavBar from "./navBar";
import Footer from "./footer";
import { IoConstruct } from "react-icons/io";

import { useState } from "react";

export default function About() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <>
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Graeme Paterson</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="bg-gradient-to-tr from-purple-50 via-purple-100 to-purple-200 dark:bg-gradient-to-tr dark:from-gray-600 dark:via-gray-700 dark:to-gray-800 px-10 md:px-20 lg:px-30">
          <NavBar darkMode={darkMode} setDarkMode={setDarkMode} />
          <section className="min-h-screen">
            <div className=" mx-24">
              <h3 className="flex justify-start ml-60 text-5xl py-1 text-seagreen dark:text-moonstone">
                About
              </h3>
            </div>
            <div className="  min-w-screen h-96 flex justify-start p-10 items-start gap-20 mt-10 rounded-xl dark:bg-transparent">
              <p1 className="text-seagreen dark:text-gray-100 ml-72">
                UNDER CONSTRUCTION
              </p1>
            </div>
          </section>
          <Footer />
        </main>
      </div>
    </>
  );
}
